# 输入一个int类型的值N，构造长度为N的数组arr并返回要求：对任意的i < k < j，满足arr[i] +arr[j] !=arr[k] * 2

In [1]:
##  左 + 右 
## 数组长度为3，只有一组
## 等效变换： 【i】+1 +【j】+1 ！= 2（【k】+1）
## 对应第几个奇数变换而来的新序列也满足以上条件
## 【3，1，2】--》【5,1,3】
## 长度 > N达标，长度=N也达标
## 序列进行奇变换 与 偶变换
##构建数组

In [2]:
import numpy as np

In [38]:
#class MakeNo:
        #生成长度为size的达标数组
        #达标：对于任意的i<k<j，满足条件
def makeNo(size):
    if size==1:               
        return np.ones((1))
    #先找一半达标
    # 向上取整 7:4
    #【4】个奇数【3】个偶
    halfsize=(size+1)>>1
    base=makeNo(halfsize)
    ans=np.zeros((size))
     
    for index in range(0,halfsize):
        ans[index]=base[index]*2+1
    index+=1
    for i in range(0,size-index):
        ans[index+i]=base[i]*2
    return ans

            

In [33]:

print(makeNo(3))

[1.]
(1,)
[0. 0.]
[3. 2.]
(2,)
[0. 0. 0.]
[7. 5. 6.]


In [35]:
def isVaild(arr):
    N=len(arr)
    for i in range(0,N):
        for k in range(i+1,N):
            for j in range(k+1,N):
                if arr[i]+arr[j]==2*arr[k]:
                    return False
    return True

In [37]:
array=makeNo(1000)
print(isVaild(array))

[1.]
(1,)
[0. 0.]
[3. 2.]
(2,)
[0. 0. 0. 0.]
[7. 5. 6. 4.]
(4,)
[0. 0. 0. 0. 0. 0. 0. 0.]
[15. 11. 13.  9. 14. 10. 12.  8.]
(8,)
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[31. 23. 27. 19. 29. 21. 25. 17. 30. 22. 26. 18. 28. 20. 24. 16.]
(16,)
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0.]
[63. 47. 55. 39. 59. 43. 51. 35. 61. 45. 53. 37. 57. 41. 49. 33. 62. 46.
 54. 38. 58. 42. 50. 34. 60. 44. 52. 36. 56. 40. 48. 32.]
(32,)
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[127.  95. 111.  79. 119.  87. 103.  71. 123.  91. 107.  75. 115.  83.
  99.  67. 125.  93. 109.  77. 117.  85. 101.  69. 121.  89. 105.  73.
 113.  81.  97.  65. 126.  94. 110.  78. 118.  86. 102.  70. 122.  90.
 106.  74. 114.  82.  98.  66. 124.  92. 108.  76. 116.  84. 100.  68.
 120.  88. 104.  72. 112.  80.  96.]

True


## 时间复杂度：T(N) = T(N/2) + O(N)  ------->(Master公式)  O(N)

### Master公式

$T(N)=a*T(\frac{N}{b})+O(N^d)$

$a$为子问题的调用次数，$b$为处理过程的时间复杂度，其中$a=1$，$b=1$

1）$log_b a < d$, 时间复杂度为$O(N^d)$

2) $log_b a > d$, 时间复杂度为$O(N^{log_b a})$

3) $log_b a = d$, 时间复杂度为$O(N^d *logN)$