In [1]:
import numpy as np

1.$A=UΣV^T$ U是m阶正交矩阵，V是n阶正交矩阵，Σ是m×n矩形对角矩阵。

2.任意给定一个实矩阵，其奇异值分解一定存在，且不唯一

3.奇异值分解包括紧奇异值分解和截断奇异值分解。紧奇异值分解是与原始矩阵等秩的奇异值分解，截断奇异值分解是比原始矩阵低秩的奇异值分解。

4.奇异值分解对应三个连续的线性变换：一个旋转变换，一个缩放变换和另一个旋转变换第一个和第三个旋转变换分别基于空间的标准正交基进行。

5.奇异值分解可以看作是矩阵数据压缩的一种方法，即用因子分解的方式近似地表示原始矩阵，这种近似是在平方损失意义下的最优近似。


In [16]:
def rebuildMatrix(U,sigma,V):
    a=np.dot(U,sigma)
    a=np.dot(a,np.transpose(V))
    return a
def sortByEigenValue(EigenValue,EigenVector):
    index=np.argsort(-1*EigenValue)## 从大到小排
    EigenValue=EigenValue[index]
    EigenVector=EigenVector[:,index]
    return EigenValue,EigenVector
def SVD(matrixA,NumofLeft=None):
    ##matrixA m*n
    matrixAT_matrixA=np.dot(np.transpose(matrixA),A)
    lambda_V,X_V=np.linalg.eig(matrixAT_matrixA)## 计算
    lambda_V,X_V=sortByEigenValue(lambda_V,X_V)
    
    sigma=lambda_V
    sigma=list(map(lambda x:np.sqrt(x) if x>0 else 0,sigma))
    sigma=np.array(sigma)
    sigmaMatrix=np.diag(sigma)## 对角矩阵
    
    if NumofLeft==None:
        rankOfSigmaMatrix=len(list(filter(lambda x:x>0,sigma)))## 大于0的特征值的个数
    else:
        rankOfSigmaMatrix=NumofLeft
    sigmaMatrix=sigmaMatrix[0:rankOfSigmaMatrix,:]## 选择前特征值
    
    ## 计算右奇异值
    X_U=np.zeros((matrixA.shape[0],rankOfSigmaMatrix))
    for i in range(rankOfSigmaMatrix):
        #print((np.dot(matrixA,X_V[:,i])/sigma[i]).shape)
        X_U[:,i]=np.transpose(np.dot(matrixA,X_V[:,i])/sigma[i])
        
    ## 对左奇异值和右奇异值进行裁剪
    X_V=X_V[:,0:NumofLeft]
    sigmaMatrix=sigmaMatrix[0:rankOfSigmaMatrix,0:rankOfSigmaMatrix]
    
    return X_U,sigmaMatrix,X_V
    
    

In [17]:

A = np.array([[1, 1, 1, 2, 2], [0, 0, 0, 3, 3], [0, 0, 0, 1, 1], [1, 1, 1, 0, 0],
              [2, 2, 2, 0, 0], [5, 5, 5, 0, 0], [1, 1, 1, 0, 0]])
A

array([[1, 1, 1, 2, 2],
       [0, 0, 0, 3, 3],
       [0, 0, 0, 1, 1],
       [1, 1, 1, 0, 0],
       [2, 2, 2, 0, 0],
       [5, 5, 5, 0, 0],
       [1, 1, 1, 0, 0]])

In [18]:
U,sigma,V=SVD(A,NumofLeft=3)

(7,)
(7,)
(7,)


In [29]:
np.dot(np.transpose(V),V)

array([[ 1.00000000e+00, -5.45586904e-19, -1.65427991e-16],
       [-5.45586904e-19,  1.00000000e+00, -5.35874657e-17],
       [-1.65427991e-16, -5.35874657e-17,  1.00000000e+00]])

In [27]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [12]:
rebuildMatrix(U,sigma,V)

array([[ 1.00000000e+00,  1.00000000e+00,  1.00000000e+00,
         2.00000000e+00,  2.00000000e+00],
       [ 1.13027077e-16,  4.79271673e-16, -6.95284616e-16,
         3.00000000e+00,  3.00000000e+00],
       [ 4.53565824e-17,  1.72064044e-16, -2.19454720e-16,
         1.00000000e+00,  1.00000000e+00],
       [ 1.00000000e+00,  1.00000000e+00,  1.00000000e+00,
        -1.68092791e-17, -1.68092791e-17],
       [ 2.00000000e+00,  2.00000000e+00,  2.00000000e+00,
        -3.36185582e-17, -3.36185582e-17],
       [ 5.00000000e+00,  5.00000000e+00,  5.00000000e+00,
        -1.46864029e-16, -1.46864029e-16],
       [ 1.00000000e+00,  1.00000000e+00,  1.00000000e+00,
        -1.38777878e-17, -1.38777878e-17]])